### ISSUE TITLE
Cannot deserialize sealed class

### ISSUE THREAD

**Issue by tihmels** [rjaros/kvision#212] opened 2020-12-21 18:00 UTC
Hi, 

I've been playing with Kvision for a few days now and it's grown into quite a decent project - I'm quite taken with it.
I use websockets with sealed classes as message type definitions. Unfortunately I just can't manage to deserialize them in the ktor backend. Could you please provide some more instructions on how to use the @JsonTypeInfo annotation?

```
@Serializable
data class CMessage(val messageType: CMessageType? = null)

@Serializable
data class SMessage(val messageType: SMessageType? = null)

@JsonTypeInfo(use = Id.CLASS, include = As.PROPERTY, property = "type", defaultImpl = JsonTypeInfo::class, visible = false)
@Serializable
sealed class CMessageType {

    var id: Int? = null

    @Serializable
    object RequestPuzzleInstance : CMessageType()

    @Serializable
    object FetchConfigData : CMessageType()

    @Serializable
    object StartBacktracking : CMessageType()

    @Serializable
    object StopBacktracking : CMessageType()

    @Serializable
    data class SetBacktrackingSpeed(val speed: Int) : CMessageType()

    @Serializable
    data class SetConfigData(val config: CSPConfiguration) : CMessageType()

}

@JsonTypeInfo(use = Id.CLASS, include = As.PROPERTY, property = "type", defaultImpl = JsonTypeInfo::class, visible = false)
@Serializable
sealed class SMessageType {

    var id: Int? = null

    @Serializable
    data class PuzzleInstance(val instance: TentGridInstance) : SMessageType()

    @Serializable
    data class ConfigurationData(val configurationData: com.example.ConfigurationData) : SMessageType()

    @Serializable
    data class AssignmentUpdate(val assignment: Assignment) : SMessageType()
}```

**Comment by rjaros** [comment] 2020-12-21 19:26
First of all - I think your code is correct. 

But I can confirm that there is some kind of problem with Ktor. And it's strange, because:
1. It seems to be Ktor specific (works without problems with other backends)
2. It fails only when the Ktor backend is run from gradle task. It works fine when I build and run production jar.

I will have to explore this problem more deeply. Perhaps it's some kind of classpath conflict with Ktor and Gradle. I'll let you know when I find something out.

**Comment by tihmels** [comment] 2020-12-22 12:57
Ah ok, interesting. 
Thank you for your fast response. 👍

**Comment by rjaros** [comment] 2020-12-22 13:01
Unfortunately I haven't found any solution for this. 
I'll try to upgrade to Ktor 1.5.0, which was released today. But perhaps I'll have to migrate from jackson to kotlinx.serialization sooner than I thought.

**Comment by rjaros** [comment] 2020-12-23 01:36
Good news - the problem is gone with Ktor 1.5.0 default configuration. Bad news - the problem is still there when new Ktor development mode is enabled. They have definitely broken something in Ktor ;-(

**Comment by tihmels** [comment] 2020-12-23 08:57
Haha 😂 but I think thats fine for the moment, actually I'm still very used to backends without hot reloading.. ;-)

**Comment by rjaros** [comment] 2020-12-28 13:15
I've migrated KVision from `jackson` to `kotlinx.serialization` in 3.19.0. The issue is fixed now, even with Ktor development mode.
And `@JsonTypeInfo` annotation is no longer required.

**Closed by rjaros** 2020-12-28 13:15 UTC
