### ISSUE TITLE
BUG - reDraw Table always happen in cellEditCancelled

### ISSUE THREAD

**Issue by PsHye** [rjaros/kvision#470] opened 2023-03-30 08:21 UTC
I've been having a problem with a Tabulator where clicking on a selector causes the table to scroll to the top. I'm wondering if there is a fix or workaround for this issue. I've checked for any misconfigurations, but haven't been able to find any solutions in the documentation. Any help would be greatly appreciated

My proposal is to enable configurability of the reDraw method within the cellEditCancelled function, or alternatively, to provide a global setting to control the entire redraw functionality of the Table.

Thanks in advance 👐🏻 

https://github.com/rjaros/kvision/blob/4d56f5eb8367ca3fe840fe2666ac17b94157011b/kvision-modules/kvision-tabulator/src/main/kotlin/io/kvision/tabulator/Tabulator.kt#L204-L211

https://user-images.githubusercontent.com/32044782/228774840-f6f16e7d-c110-486e-a64d-7e11e1a94b69.mp4

**Comment by rjaros** [comment] 2023-03-30 11:35
There are two issues here. When editing a cell we can leave the editor by entering new data (saving) or just clicking outside of the editor (cancelling). I've fixed the issue with cancelling, because it was broken in KVision code.

But there was still an issue with saving and it seems to be a bug in Tabulator (unfortunately not easy to reproduce without KVision, so I haven't reported it).  I've come up with a workaround and used this as well. Please test when new release is ready.

**Comment by rjaros** [comment] 2023-04-09 06:49
Fixed in 6.3.0

**Closed by rjaros** 2023-04-09 06:49 UTC
