### ISSUE TITLE
Shrinking windows in desktop example

### ISSUE THREAD

**Issue by mgrouch** [rjaros/kvision#433] opened 2022-08-30 21:41 UTC
If I open several windows in desktop example
Then if I press Ctrl - several times, to change browser scale

Some windows will start slowly shrinking till they completely disappear. 

Thanks

**Comment by rjaros** [comment] 2022-08-31 09:22
What browser do you use? I can't reproduce neither on Firefox nor on Chrome.

**Comment by mgrouch** [comment] 2022-08-31 12:03
It’s reproducible for me in Chrome and Edge

**Comment by rjaros** [comment] 2022-08-31 12:30
I've tested on Windows and Linux and still can't reproduce. Do you open the current showcase example published online: https://rjaros.github.io/kvision-examples/showcase/#!/windows ?

Could you please record a short video with this issue?

**Comment by mgrouch** [comment] 2022-08-31 13:51
Not in showcase

desktop example. 

I’ll try to make video

**Comment by mgrouch** [comment] 2022-08-31 14:43
https://user-images.githubusercontent.com/8263013/187707154-224234b2-ebc4-4c3f-8bca-a74bacaeee1e.mov

**Comment by mgrouch** [comment] 2022-08-31 16:44
It looks like some rounding issue when something converts into integer pixels.
Might be rounding algorithm which is used has a bias into one direction.
I might be wrong too.

**Comment by rjaros** [comment] 2022-09-13 16:39
Fixed in 5.15.0

**Closed by rjaros** 2022-09-13 16:39 UTC
