### ISSUE TITLE
DateTime picker shows AM/PM for 24-hour input

### ISSUE THREAD

**Issue by Stephen-Hamilton-C** [rjaros/kvision#480] opened 2023-06-12 15:17 UTC
In the [KVision Showcase](https://rjaros.github.io/kvision-examples/showcase/#/forms) forms tab, the Time field display is in 24-hour time, but when you bring up the time picker, the input shows 12-hour time. While it still works fine, this is rather off-putting. I have experienced this same problem in my own code

**Comment by rjaros** [comment] 2023-06-12 16:50
Hello.
The problem is caused by the time format used by `DateTime` component. Currently it's hard-coded as "HH:mm" and doesn't take into account the browser locale. On the other hand, the time picker (TempusDominus) does support locale settings.
As a temporary workaround you can try using `DateTime(format = "hh:mm A")` to use 12-hour time format in the input field. And I'll try to check if it's possible to automatically reuse TempusDominus locales settings and auto-detect the correct format.

**Comment by rjaros** [comment] 2023-07-03 14:46
Fixed in 6.5.0

**Closed by rjaros** 2023-07-03 14:46 UTC
