### ISSUE TITLE
TomSelect is not searchable when placeholder == null

### ISSUE THREAD

**Issue by shananton** [rjaros/kvision#483] opened 2023-06-29 22:34 UTC
The `TomSelectInput` component has this line in `getSettingsObj()`:
```
if (placeholder == null) this.controlInput = null
```

This disables some built-in `TomSelect` functionality, including being able to search options, and almost turns it into a simple `Select`. I'm not sure what's the logic behind this (why should the lack of a placeholder stop the user from being able to search?) and I could not find mentions of this in the docs...

I'd appreciate if you could either fix this or elaborate why it's done as it is (and maybe update the docs) :upside_down_face:

**Comment by rjaros** [comment] 2023-07-02 11:12
There were two reasons for this:
1. `TomSelect` was designed as a replacement for the old `BootstrapSelect` component from KVision 5, which had a search option but was not searchable by default.
2.  I had some issues with strange wrapping of TomSelect control on smaller screens, caused by the empty search input. Showing this input only when the placeholder was defined fixed the problem.

I agree these are not very strong arguments and I'm willing to remove this constraint. I'll just add a new `disableSearch` option to make it explicit.

**Comment by rjaros** [comment] 2023-07-03 14:45
Fixed in 6.6.0

**Closed by rjaros** 2023-07-03 14:45 UTC
