### ISSUE TITLE
Placeholder parameter of TabulatorOptions not working

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#335] opened 2022-01-14 21:34 UTC
Is the "placeholder" parameter of the TabulatorOptions implemented yet in KVision.  I added line below but it's not working and I still get the data load error below:
```
 placeholder = "No data available",
``

 Data Load Error:  TypeError: Cannot read properties of undefined (reading 'length')

**Comment by rjaros** [comment] 2022-01-15 13:45
The `placeholder` option is working fine for me. The given message is displayed when the tabulator data is empty. But empty data is not an error, you should not see any message in the console. Your error is probably caused by some other condition. Please give some more information / code.

**Comment by rjaros** [comment] 2022-01-30 06:22
Looks like duplicate of #339

**Closed by rjaros** 2022-01-30 06:22 UTC
Labels: duplicate
